SELECT * FROM customer;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) as revenue FROM customer group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount FROM customer WHERE discount_applied = 'Yes' and 
purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
-- as the review_rating is considered as double prcison we are typecasting it to numeric to work with round
SELECT item_purchased, ROUND(AVG(review_rating)::numeric,2) as average_product_rating 
FROM customer group by item_purchased order by AVG(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer 
WHERE shipping_type= 'Standard' or shipping_type = 'Express' group by shipping_type;
-- OR
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer 
WHERE shipping_type in ('Standard','Express') group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend, SUM(purchase_amount) as total_revenue 
FROM customer group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(SUM(CASE WHEN discount_applied = 'Yes' then 1 ELSE 0 END)* 100.0/COUNT(*),2) as percentage_of_purchases , 
COUNT(*) as item_purchased_count
FROM customer group by item_purchased order by percentage_of_purchases desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as(
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 then 'New'
	 WHEN previous_purchases BETWEEN 2 and 10 then 'Returning'
	 ELSE 'Loyal'
	 END as customer_segment
FROM customer
)
SELECT customer_segment, count(*) as number_of_customers FROM customer_type group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with ranked_products as (
SELECT item_purchased, category, COUNT(*) as total_purchases,
ROW_NUMBER() OVER(partition by category order by COUNT(customer_id) desc) as item_rank
FROM customer group by category, item_purchased
)

SELECT item_rank, item_purchased, category, total_purchases FROM ranked_products WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as total_purchases FROM customer 
WHERE previous_purchases > 5 group by subscription_status order by total_purchases desc;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue FROM customer group by age_group order by total_revenue desc;